apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test
  name: test
spec:
  containers:
  - image: curlimages/curl:8.18.0
    name: test
    command: ["/bin/sh", "-c", "sleep 99999"]
    resources: 
      requests:
        cpu: 1m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
